let item_1 = 5;
console.log(item_1);
let item_2 = 3;
console.log(item_2);
let item_3 = item_1 + item_2;
console.log(item_3);
let item_4 = "Hello world";
console.log(item_4);
console.log(item_3 + item_4);
console.log(item_3 * item_4);
let item_5 = item_3;
let item_6 = 15;
let item_6_type = typeof item_6;
let aa = "item_6 == ";
let bb = "item_6_type == ";
console.log(aa + item_6 + ", " + bb + item_6_type);
let item_7 = String(item_6);
let item_7_type = typeof item_7;
let cc = "item_7 == ";
let dd = "item_7_type == ";
console.log(cc + item_7 + ", " + dd + item_7_type);