let n = 3;
let nn = n + String(n);
nn = +nn;
console.log(nn);
console.log(typeof nn);
let nnn = nn + String(n);
nnn = +nnn;
console.log(nnn);
console.log(typeof nnn);
let sum = (n + nn + nnn);
console.log(sum);
